### ISSUE TITLE
ChiefOnboarding v2.0 release

### ISSUE THREAD

**Issue by GDay** [chiefonboarding/ChiefOnboarding#152]
Alright, so everything is almost ready to be pushed to master. The code has been tested quite well (and has a 93% test coverage), though it could still use some more test cases, especially with the custom integrations and perhaps on the frontend.

If all goes well, then everything will be merged on **Thursday**!

To summarize (and keep track of what needs to be done):

* Completely new look
* Moved from SPA back to MPA (dropped almost all javascript requirements)
* Support for custom integrations and webhooks created by you (https://integrations.chiefonboarding.com / https://github.com/chiefonboarding/ChiefOnboarding/blob/v2.0/docs/Integrations.md)!
* Sequence timed based triggers can now be triggered at a custom time (used to be always at 8 am)
* Slack doesn't need to depend on webhooks anymore - websocket is now supported as well (so you can also use it without having a public access point).
* Notifications on both the new hire and admin side on various actions
* Change channel where bot sends messages to
* Change admin to manager and vise versa
* Change email template
* Assign admin tasks in sequence to admin/manager instead of a specific person
* Docs have been updated and added into the main repository on the v2.0 branch (not live on a website yet, but see the `docs` folder)

BREAKING CHANGES:
* Scheduled access items that have been scheduled on the old version will not be executed anymore - table is dropped and functionality has been replaced
* Slack account creation integration will be dropped due to dropped support from Slack. It can be put back later, but requires some changes.
* API is currently dropped, but will be back later.

Implemented for release:
- [x] #147 
- [x] #144 
- [x] #141 (general idea to webhooks / custom integrations)
- [x] #129 
- [x] #128 
- [x] #124 
- [x] #123 
- [x] #122 
- [x] #120 
- [x] #104 (this shouldn't be a problem anymore as it's not decoupled anymore)
- [x] #92 (message that uploading is disabled)
- [x] #27 
- [x] #24
- [x] #22 (general option to send message after integration/webhook trigger)  
- [x] #21
- [x] #15
- [x] #13
- [x] #12
- [x] #5 
- [ ] Update Slack docs (new manifest)
- [ ] Add other languages back (hiring people to make the translations)
- [ ] Bug bash - Wanna join? [Email me](mailto:hello@chiefonboarding.com) and I will set up an instance for you to play around with.
- [ ] Test database migrations. Lots of data has been moved around, double check that everything is still correct after deployment of new version.

To be done right after release:
- [ ] #142
- [ ] #140 (will create this integration when I have a minute - if not too complicated)
- [ ] #138 (this has been removed - need to recreate a legacy version and enterprise version)

**Comment by GDay** [comment]
@woakes070048 Yeah, I doing the best I can. There are a few bugs left in the sequences that I need the fix. The rest is working fine. Should be ready for production early next week.

**Comment by GDay** [comment]
@woakes070048 This will be merged on Thursday.

**Comment by woakes070048** [comment]
@GDay thanks I look forward to trying this out.

**Comment by MuratDoganer** [comment]
We all really appreciate it @GDay <3

**Comment by GDay** [comment]
Well, this was a long day. So, I have just merged everything into master. I did a lot of testing today and most things seem to work fine, but will do more battle-testing in the next few days. I have one issue still standing where courses/resources don't update the modal when it's opened in Slack. It works locally, but not on my staging server, not sure what's going on there, but will give that another go tomorrow. 

As always: use at your own risk and create a backup before updating. There are a lot of migrations that will be ran.

I have also updated the main post above with all the breaking change that I noticed.

One of the main features for this release is the webhook/integration option. You can now create your own integrations, like this one: https://integrations.chiefonboarding.com/d/1-asana-account-creation. This can then be used in a sequence. I will be creating more of those integrations with different services. Docs: https://github.com/chiefonboarding/ChiefOnboarding/blob/master/docs/Integrations.md

For some reason the docs workflow crashed, so the site is not up to date yet, but will fix that tomorrow.

Please report any bugs, so I can fix them :)

**Comment by MuratDoganer** [comment]
Hey @GDay loving v2! It looks so gorgeous! 

Ran into a slight issue with the slackbot, Ive updated the url as suggested above, but the bot itself has completely stopped working :D 

I am going to create a new test env so I can see if its just that particular bot

**Comment by GDay** [comment]
@MuratDoganer Oh, that's not good. Are you using the web socket or not?

If you are not using the socket, then see this (as mentioned above):

> You can update Slack to use the internal websocket instead of the HTTPS calls webhooks. That way, you remove one open endpoint (technically, you could use the app now with Slack behind a VPN). Websocket is the default. If you don't want to use the websocket, then you will have to add SLACK_USE_SOCKET to False in your environment variables. It will then fall back to the "old" url and webhooks. It's important that you set this variable AFTER all migrations have ran.

If you are using the socket, then you will need to create an app token, see docs: https://github.com/chiefonboarding/ChiefOnboarding/blob/master/docs/Deployment.md#slack-bot

**Comment by GDay** [comment]
@MuratDoganer Strange, in your Heroku logs, does it hit the webhook url when you write something to the bot? That should return a 200 status code.

**Comment by MuratDoganer** [comment]
@GDay Interesting, no it does not. Nothing comes up in the logs at all

I did use the new token under the SLACK_APP_TOKEN env, sockets are on, maybe ill try falling back to the old way and see what happens

**Comment by GDay** [comment]
Wait, you are currently using websockets, is that right?

If that's the case, then you should not have the `SLACK_USE_SOCKET` environment variable. It's on by default, so you don't need it.
You will also need:
`SLACK_APP_TOKEN` and `SLACK_BOT_TOKEN` as environment variables.

But yeah, perhaps good to fall back to webhooks for now until we get down to the issue.

**Comment by MuratDoganer** [comment]
Ah I was missing the `SLACK_BOT_TOKEN`, i've added it in and I am seeing activity from the bot now in the logs

However trying to run any kind of command leads to this:

```Failed to process a message: cannot schedule new futures after shutdown
2022-07-08T16:10:16.942420+00:00 app[worker.1]: Traceback (most recent call last):
2022-07-08T16:10:16.942421+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/slack_sdk/socket_mode/client.py", line 155, in process_messages```

**Comment by MuratDoganer** [comment]
So I've reverted back to the old urls, still no slackbot responses but, i do now see the correct message in the logs

`[08/Jul/2022:16:22:10 +0000] "POST /api/slack/bot HTTP/1.1" 200 0 "-" "Slackbot 1.0 (+https://api.slack.com/robots)"`

**Comment by GDay** [comment]
Hmm... could you run this please? Go into heroku and click on "more" and then "run console". Then type in "bash" and hit "run", Then do "cd back" and then run "python manage.py shell". That will get us a python shell.

Then type:
```
from admin.integrations.models import Integration
print(Integration.objects.filter(integration=0).count())
```

If that shows anything more than 1, then that might be the issue. It will always take the first one. If you have tried to add the slack bot multiple times in the past, then the first one might have an old/invalid token.

**Comment by MuratDoganer** [comment]
Yes you are correct, I did indeed get back `1`

**Comment by GDay** [comment]
If it got back 1, then that's not the issue. Very strange. I can't seem to replicate it on my side. It looks like Slack recognizes that you sent a message, but for some reason refuses to send one back. 

Let's see if you can send a message manually.

Go back into the shell again with the instructions above. Then get your slack user id:

```
from users.models import User
u = User.objects.get(email="youremail@....com")
print(u.slack_user_id)
```
Send a slack message:
```
from slack_bot.utils import Slack
Slack().send_message(channel=u.slack_user_id, text="test message")
````

**Comment by MuratDoganer** [comment]
Yeah nothing is coming through, no error message either! 

But in the other environment (from new) its working fine, so weird

**Comment by GDay** [comment]
Hmm... I have found an issue with websockets that may be the cause why it wasn't responding back to you. I have just merged a PR for that. Perhaps you could try it again with the new update?

Also, is it just messages that don't work, or does it also not react to buttons?

**Comment by GDay** [comment]
Oh, also, it does actually safe error messages when sending message (but it doesn't display those yet). It saves notifications. You can get the last one with (within shell):

```
from organization.models import Notification
note = Notification.objects.filter(notification_type="failed_send_slack_message").last()
print(note.description)
```

**Comment by GDay** [comment]
Alright, so at least on Heroku (not sure about other platforms), the websocket requests are incredibly unstable. I am constantly getting requests that take way too long and therefore timeout/crash.

The previous error:
```
File "/app/.heroku/python/lib/python3.9/site-packages/slack_sdk/socket_mode/client.py", line 155, in process_messages
```
seems to be related to the python version. With Python 3.8, it works fine. Both 3.9 and 3.10 show the error. Could also be related to Heroku, I am not entirely sure.  

On local host (for development), I have never gotten them - it's always been fine. I am not sure why it's slow, perhaps Heroku doesn't like the threading that we need to do to keep the websocket up and alive. I have now set `SLACK_USE_SOCKET` to `False` by default and I would recommend using the webhooks for now.

If you want to do a query to Slack directly (using their library), then you can do this (through shell again):
```
from admin.integrations.models import Integration
from slack_bolt import App as SlackBoltApp
from users.models import User

u = User.objects.get(email="youremail@....com")
integration = Integration.objects.filter(integration=0).first()                                                                                                                                                          
client = slack_sdk.WebClient(token=integration.token)
client.chat_postMessage(channel=u.slack_user_id, text="Whatever you want to say")
```

If it errors, Slack will raise an exception that will be printed out in your console.

**Comment by MuratDoganer** [comment]
Okay, getting this:

`redirect_uri did not match any configured URIs. Passed URI: https://mycompaniesurlforchief.com`

**Comment by GDay** [comment]
In your Slack app settings: https://api.slack.com/apps.

Go to "OAuth & Permissions" and change the "redirect url" to `https://mycompaniesurlforchief.com/admin/integrations/slack` (swap the url with yours). You probably have "api" instead of "admin" in the url right now.

Not sure why you are getting that though, because that url is not used for slack messages, I think.

**Comment by MuratDoganer** [comment]
I dont know why, but that did fix it

I can only speculate it wasnt authorising properly?

**Comment by MuratDoganer** [comment]
Yeah that was the error message I got when I used the code above. 

It's odd, but changing `/api/` to `/admin/` like you suggested worked, I am now getting messages in Slack again

**Comment by Kuuchuu** [comment]
@GDay Is there a way to verify which version I am currently running? Thanks for all your work on this project!

**Comment by GDay** [comment]
@Kuuchuu You are welcome! That kinda depends on how you run chiefonboarding. If that's through heroku, then you can just check the commit that is on the heroku server. (or just push it and it will either update or tell you it's up to date). 

If you are using Docker, then you are probably still on the old version. Will push a new docker image in a few hours.

**Comment by MuratDoganer** [comment]
Another bug: In heroku latest build; duplicating a sequence returns a Server Error (500)

**Comment by GDay** [comment]
@MuratDoganer Thanks for reporting that. I have just fixed it (just merged the PR). I have noticed that there are some performance issues with duplicating very large sequences. It can take several seconds before it's done. I might need to move it to a background task, not sure yet, but duplicating should work now (with a little patience, haha).

**Comment by MuratDoganer** [comment]
Thanks @GDay you're a real legend :) 

If you need a tester I am happy to help haha

**Comment by MuratDoganer** [comment]
Found another one! Uploading files / pdfs, get an upload failed message (I do have aws s3 settings in my env in heroku)

Does this need a new integration?

**Comment by GDay** [comment]
Thanks. Nope it doesn't need an integration - only the environment variables. 

Small typo caused that: https://github.com/chiefonboarding/ChiefOnboarding/pull/183/files

Merged into `master` now!

**Comment by MuratDoganer** [comment]
Updated, checked, same file upload failed 

Let me do another test to make sure its not anything else on my side!

**Comment by GDay** [comment]
You could check the network tab in your browser. When you are uploading a file it should make two requests: one should return a url (presigned url to upload to) and the second request should be the actual uploading to AWS (or equivalent). If any of those two fails, then it's likely one of the environment variables.

**Comment by MuratDoganer** [comment]
Yup that looks okay, no failures in Network tab, but console is showing this message:

```Block «paragraph» skipped because saved data is invalid```

**Comment by GDay** [comment]
Yeah, that's because it failed for some reason (and then the editor doesn't save the block). 

So you get this, right?

![image](https://user-images.githubusercontent.com/1939656/178511851-6ad956ce-0b29-44a7-a28a-bbd5ffb55be4.png)

Or maybe it cached some of the javascript? Perhaps try in incognito?

**Comment by MuratDoganer** [comment]
Hmm, yes but in Incognito I got this:

```Failed to load resource: the server responded with a status of 500 (Internal Server Error)```

**Comment by MuratDoganer** [comment]
Yeah thats all good, tested outside chief and is working as expected there - was also working in v1

Ill run that and see what it says one moment

**Comment by GDay** [comment]
I have no clue. It's so weird. I have tested it in Linux (firefox) and on Windows (chrome and firefox) and all seem to work just fine on my demo server. Tested in templates as well as in the sequence.

Could you try a different file? And perhaps in a different place in the app (shouldn't matter, but who knows)?

**Comment by MuratDoganer** [comment]
Yep tried different files at different sizes, pdfs, images, etc none work

I am thinking I might just spin it up in Render and see how I get on there (we are testing after all!)

**Comment by MuratDoganer** [comment]
btw: running it locally in dev mode; works fine! 

I am thinking this is Heroku specific at this rate

**Comment by GDay** [comment]
I am using Heroku too and it works fine for me there.

**Comment by MuratDoganer** [comment]
I think I will try creating a new s3 bucket and see if that fixes it

Also noticed: If I add the slackbot to a channel, then update the channel list in chief, it doesnt appear in the settings - it only shows general still :)

**Comment by MuratDoganer** [comment]
Is this the correct CORS for s3?

```[
    {
        "AllowedHeaders": [
            "*"
        ],
        "AllowedMethods": [
            "PUT",
            "POST",
            "DELETE",
            "GET"
        ],
        "AllowedOrigins": [
            "https://chief.onboarding.com"
        ],
        "ExposeHeaders": []
    }
]```

**Comment by GDay** [comment]
> Also noticed: If I add the slackbot to a channel, then update the channel list in chief, it doesnt appear in the settings - it only shows general still :)

Try this:

![image](https://user-images.githubusercontent.com/1939656/179844101-4e389193-8dd6-474e-9264-733e9eeecc20.png)

It's poorly documented, I know. Will fix that.

Yeah, that CORS looks fine. Obviously, change the url in `AllowedOrigins`.

**Comment by MuratDoganer** [comment]
Yup! Pressed that! I've also made sure that its a public channel and not private

I can see the bot in the channels "added integrations" tab, when I go to chief and update slack I get a success message, then under the slackbot settings - it still only shows `general` and nothing else

**Comment by MuratDoganer** [comment]
@GDay Even with a new s3 bucket running a fresh Render install I cannot upload files into a resource

But

I can upload logos, images, etc everywhere else. Its only when I go to Templates > Resource > press + > then select "Attaches" I get an upload failed error

In the same block, if I upload an Image, or a video - it works without problem 

The issue seems to be with the "attaches" button

**Comment by GDay** [comment]
> Yup! Pressed that! I've also made sure that its a public channel and not private

Just debugged this a bit. Looks like Slack changed their permissions and it now also needs `channels:read`. I am going to fix that with a new commit in the PR that's currently open (which also fixes some other bugs) soon.

> I can upload logos, images, etc everywhere else. Its only when I go to Templates > Resource > press + > then select "Attaches" I get an upload failed error

It's super strange, because that does work for me. Tested locally on my pc and also on the staging server (which both use different buckets). 

If you are up to debug this a bit, then I have created a new branch in this repo: https://github.com/chiefonboarding/ChiefOnboarding/tree/debug-uploading-files. The last commit are just some `console.log` lines to see where it gets stuck.

**Comment by MuratDoganer** [comment]
Ah okay good to know! 

Happy to help you debug this error, whats the best way to get that new branch in Render? Is it the Enable PR Previews?

**Comment by GDay** [comment]
![image](https://user-images.githubusercontent.com/1939656/179854571-e6a88346-0c02-4d20-a76a-b2e320924169.png)

I think you can change that? and then hit "deploy from latest commit"

**Comment by MuratDoganer** [comment]
How on earth did I miss that wow - ill post the logs for you in just a moment >.<

**Comment by MuratDoganer** [comment]
Looks like some errors during deploy:

```Jul 19 11:03:18 PM  --- Logging error ---
Jul 19 11:03:18 PM  Traceback (most recent call last):
Jul 19 11:03:18 PM    File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
Jul 19 11:03:18 PM      self.connect()
Jul 19 11:03:18 PM    File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
Jul 19 11:03:18 PM      return func(*args, **kwargs)
Jul 19 11:03:18 PM    File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 200, in connect
Jul 19 11:03:18 PM      self.connection = self.get_new_connection(conn_params)
Jul 19 11:03:18 PM    File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
Jul 19 11:03:18 PM      return func(*args, **kwargs)
Jul 19 11:03:18 PM    File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
Jul 19 11:03:18 PM      connection = Database.connect(**conn_params)
Jul 19 11:03:18 PM    File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
Jul 19 11:03:18 PM      conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
Jul 19 11:03:18 PM  psycopg2.OperationalError: connection to server at "dpg-cb65arf6d9kkih3hamng-a" (10.202.119.188), port 5432 failed: Connection refused
Jul 19 11:03:18 PM      Is the server running on that host and accepting TCP/IP connections?
Jul 19 11:03:18 PM  
Jul 19 11:03:18 PM  
Jul 19 11:03:18 PM  The above exception was the direct cause of the following exception:
Jul 19 11:03:18 PM  
Jul 19 11:03:18 PM  Traceback (most recent call last):
Jul 19 11:03:18 PM    File "/usr/local/lib/python3.9/site-packages/django_q/cluster.py", line 345, in pusher
Jul 19 11:03:18 PM      task_set = broker.dequeue()
Jul 19 11:03:18 PM    File "/usr/local/lib/python3.9/site-packages/django_q/brokers/orm.py", line 67, in dequeue
Jul 19 11:03:18 PM      if tasks:
Jul 19 11:03:18 PM    File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 284, in __bool__
Jul 19 11:03:18 PM      self._fetch_all()
Jul 19 11:03:18 PM    File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1324, in _fetch_all
Jul 19 11:03:18 PM      self._result_cache = list(self._iterable_class(self))
Jul 19 11:03:18 PM    File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 51, in __iter__
Jul 19 11:03:18 PM      results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
Jul 19 11:03:18 PM    File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1173, in execute_sql
Jul 19 11:03:18 PM      cursor = self.connection.cursor()
Jul 19 11:03:18 PM    File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
Jul 19 11:03:18 PM      return func(*args, **kwargs)
Jul 19 11:03:18 PM    File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 259, in cursor
Jul 19 11:03:18 PM      return self._cursor()
Jul 19 11:03:18 PM    File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 235, in _cursor
Jul 19 11:03:18 PM      self.ensure_connection()
Jul 19 11:03:18 PM    File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
Jul 19 11:03:18 PM      return func(*args, **kwargs)
Jul 19 11:03:18 PM    File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
Jul 19 11:03:18 PM      self.connect()
Jul 19 11:03:18 PM    File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
Jul 19 11:03:18 PM      raise dj_exc_value.with_traceback(traceback) from exc_value
Jul 19 11:03:18 PM    File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
Jul 19 11:03:18 PM      self.connect()
Jul 19 11:03:18 PM    File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
Jul 19 11:03:18 PM      return func(*args, **kwargs)
Jul 19 11:03:18 PM    File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 200, in connect
Jul 19 11:03:18 PM      self.connection = self.get_new_connection(conn_params)
Jul 19 11:03:18 PM    File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
Jul 19 11:03:18 PM      return func(*args, **kwargs)
Jul 19 11:03:18 PM    File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
Jul 19 11:03:18 PM      connection = Database.connect(**conn_params)
Jul 19 11:03:18 PM    File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
Jul 19 11:03:18 PM      conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
Jul 19 11:03:18 PM  django.db.utils.OperationalError: connection to server at "dpg-cb65arf6d9kkih3hamng-a" (10.202.119.188), port 5432 failed: Connection refused
Jul 19 11:03:18 PM      Is the server running on that host and accepting TCP/IP connections?
Jul 19 11:03:18 PM  
Jul 19 11:03:18 PM  
Jul 19 11:03:18 PM  During handling of the above exception, another exception occurred:
Jul 19 11:03:18 PM  
Jul 19 11:03:18 PM  Traceback (most recent call last):
Jul 19 11:03:18 PM    File "/usr/local/lib/python3.9/logging/__init__.py", line 1083, in emit
Jul 19 11:03:18 PM      msg = self.format(record)
Jul 19 11:03:18 PM    File "/usr/local/lib/python3.9/logging/__init__.py", line 927, in format
Jul 19 11:03:18 PM      return fmt.format(record)
Jul 19 11:03:18 PM    File "/usr/local/lib/python3.9/logging/__init__.py", line 663, in format
Jul 19 11:03:18 PM      record.message = record.getMessage()
Jul 19 11:03:18 PM    File "/usr/local/lib/python3.9/logging/__init__.py", line 367, in getMessage
Jul 19 11:03:18 PM      msg = msg % self.args
Jul 19 11:03:18 PM  TypeError: not all arguments converted during string formatting
Jul 19 11:03:18 PM  Call stack:
Jul 19 11:03:18 PM    File "/app/manage.py", line 69, in <module>
Jul 19 11:03:18 PM      main()
Jul 19 11:03:18 PM    File "/app/manage.py", line 17, in main
Jul 19 11:03:18 PM      execute_from_command_line(sys.argv)
Jul 19 11:03:18 PM    File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
Jul 19 11:03:18 PM      utility.execute()
Jul 19 11:03:18 PM    File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
Jul 19 11:03:18 PM      self.fetch_command(subcommand).run_from_argv(self.argv)
Jul 19 11:03:18 PM    File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
Jul 19 11:03:18 PM      self.execute(*args, **cmd_options)
Jul 19 11:03:18 PM    File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
Jul 19 11:03:18 PM      output = self.handle(*args, **options)
Jul 19 11:03:18 PM    File "/usr/local/lib/python3.9/site-packages/django_q/management/commands/qcluster.py", line 22, in handle
Jul 19 11:03:18 PM      q.start()
Jul 19 11:03:18 PM    File "/usr/local/lib/python3.9/site-packages/django_q/cluster.py", line 78, in start
Jul 19 11:03:18 PM      self.sentinel.start()
Jul 19 11:03:18 PM    File "/usr/local/lib/python3.9/multiprocessing/process.py", line 121, in start
Jul 19 11:03:18 PM      self._popen = self._Popen(self)
Jul 19 11:03:18 PM    File "/usr/local/lib/python3.9/multiprocessing/context.py", line 224, in _Popen
Jul 19 11:03:18 PM      return _default_context.get_context().Process._Popen(process_obj)
Jul 19 11:03:18 PM    File "/usr/local/lib/python3.9/multiprocessing/context.py", line 277, in _Popen
Jul 19 11:03:18 PM      return Popen(process_obj)
Jul 19 11:03:18 PM    File "/usr/local/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
Jul 19 11:03:18 PM      self._launch(process_obj)
Jul 19 11:03:18 PM    File "/usr/local/lib/python3.9/multiprocessing/popen_fork.py", line 71, in _launch
Jul 19 11:03:18 PM      code = process_obj._bootstrap(parent_sentinel=child_r)
Jul 19 11:03:28 PM  22:03:28 [Q] INFO Process-1:3 stopped pushing tasks
Jul 19 11:03:29 PM  22:03:29 [Q] ERROR reincarnated pusher Process-1:3 after sudden death
Jul 19 11:03:29 PM  22:03:29 [Q] INFO Process-1:4 pushing tasks at 16

**Comment by GDay** [comment]
Oh, I added debug info to the frontend, not backend. Looks like your database URL is not correctly set again (?). The error says that you cannot connect to the database. (unrelated to the thing we are trying to debug)

**Comment by MuratDoganer** [comment]
Yeah I noticed that too, but just triple checked the database URL and this time its identical

**Comment by GDay** [comment]
Hmmm.. maybe try to suspend both the database and server, then start the database first and then start the web service? I am really not sure why you are getting that error now if the credentials are still correct.

**Comment by MuratDoganer** [comment]
Okay will try that once the deploy finishes successfully

**Comment by GDay** [comment]
Oh, could also be the case that the error is just gone after you deployed. If you can visit the site after deployment, then it should be alright.

**Comment by MuratDoganer** [comment]
Seeing this in console: `jquery-3.5.1.min.js:2          POST https://myorg.com/api/org/file 500` which wasnt showing before

**Comment by GDay** [comment]
That's a backend error. Related to the database that is not connecting, maybe? Can you visit other pages in the app?

**Comment by MuratDoganer** [comment]
Yeh everything else works perfectly fine, including uploading pictures and videos - that error comes up on Attaches

**Comment by GDay** [comment]
Interesting. That's good, so now we at least know where the error comes from. Can you check the data that is passed through with the url? 

It should look like this:
![image](https://user-images.githubusercontent.com/1939656/179858792-645ccd12-720d-48d7-9185-80c4992b2178.png)

That should be the file name. Does it do that?

**Comment by GDay** [comment]
I have now also added debug lines to the backend and wrapped the function that's crashing in a try/catch so it should print the actual error in the backend logs now.

**Comment by MuratDoganer** [comment]
Hey @GDay There is no data being passed like in your example

Also checking the logs today there are no error logs (only the upload failed in the front end), in the backend I get this:

```Jul 20 12:18:20 PM  ext:  pdf
Jul 20 12:18:20 PM  key: 19-Colour Personality Test - Murat/Colour Personality Test - Murat.pdf
Jul 20 12:18:20 PM  full_key: https://fd-landtech.s3.eu-west-2.amazonaws.com/fd-landtech/19-Colour%20Personality%20Test%20-%20Murat/Colour%20Personality%20Test%20-%20Murat.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=[REDACTEDID]%2F20220720%2Feu-west-2%2Fs3%2Faws4_request&X-Amz-Date=20220720T111820Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=[redactedkey]

**Comment by GDay** [comment]
Wait, so there wasn't a 500 error this time?

That data is being parsed though, otherwise you would not get those debug lines.

What did your console (in your browser) print out?

**Comment by MuratDoganer** [comment]
Yeah its very weird 

This time console did not spit anything out at all; just the front end ui saying "file upload failed"

**Comment by GDay** [comment]
Yeah, I am pretty much out of ideas. It should have posted something in the console (in your browser)

I have been trying multiple different types of files, different file sizes, different names even files without an extension. I cannot seem to reproduce your issue. All files work fine.

What I am wondering is, could it be an extension in your browser maybe? Could you try on a different computer, or have someone else try to upload a file? 

That way we could at least rule out that something on your computer might be causing this issue.

**Comment by MuratDoganer** [comment]
Hmm maybe - I’ll try in a different browser tomorrow 

but I get the same error in mobile 
![9B25A80D-4C2A-471F-9D2C-5B3A71C712CE](https://user-images.githubusercontent.com/67741877/180319444-b6e65044-1813-400e-b9d0-c60b58a55fe7.jpeg)

**Comment by GDay** [comment]
Hm... looks like uploading files (and images) in resources is indeed broken. I have just been able to reproduce the issue. It does work in to do items though (in my case).

**Comment by GDay** [comment]
Okay, so I have updated the resources thing and that should be working now. I have also rebased that `debug-uploading-files` branch with those fixes. Hopefully we get more details now on what goes wrong. But perhaps it's fixed now, since uploading files to resources was indeed broken.

**Comment by MuratDoganer** [comment]
@GDay Sorry was on holiday and couldn't reply! Yes that fixed it! :D Uploads are now working as intended :) 

Quick query about the Slack channel selector, is there a way to search channels? We have the bot in a single channel, but the list is showing almost every public channel and there seems to be a limit so we cannot actually see the channel we want :D

**Comment by GDay** [comment]
Hope you enjoyed your holiday! 

> Uploads are now working as intended :)

Awesome!

> We have the bot in a single channel, but the list is showing almost every public channel and there seems to be a limit so we cannot actually see the channel we want :D

Sounds like you guys have more than 100 channels? There is a limit of `100` channels per query. in PR #213 I have increased the max amount of channels to 1000, so hopefully that does the trick. If there are more than 1000 channels, then I would have to implement pagination and do multiple calls to get all.

**Comment by GDay** [comment]
Just merged that. Once you deploy the new version, go to `settings` -> `integrations` -> `Update Slack channels list`. 

Also, just to make sure you aren't scrolling through a 1000 channels now, lol, you can search if you type in the field:

![image](https://user-images.githubusercontent.com/1939656/183894354-c4d01f0a-ad3a-4db9-a62c-36fd3eaf97b0.png)

**Comment by MuratDoganer** [comment]
Perfect! 

Yeah we have a _ton_ of slack channels...there seems to be one new channel everyday hahaha

**Comment by MuratDoganer** [comment]
Ooo found one more! 

I cant seem to promote anyone beside myself to Admin

When I try to add a new admin, it says "user with email already exists", and no option to upgrade user (added via slack) to admin!

**Comment by GDay** [comment]
Thanks for letting me know! Will be fixed with PR #214!

**Comment by MuratDoganer** [comment]
Thats fixed it! Thanks GDay :) 

I have one more question; We currently use a Typeform to automate some onboarding tickets, and the HR team wanted to know if there was a way to trigger a New Hire via TypeForm: i.e. they fill in the form in TypeForm and that will send the info to Chief who then creates a New Hire with that info?

I'd imagine I would need to create an Integration?

**Comment by GDay** [comment]
> I'd imagine I would need to create an Integration?

Integrations (for now) are only from a new hire to an external platform. I.e. From COB -> Asana to create an account. What you are suggesting is the other way around. 

> i.e. they fill in the form in TypeForm and that will send the info to Chief who then creates a New Hire with that info?

There are currently 3 ways of creating new hires:

1. Manually by filling in the form in the dashboard.
2. Using Slack to create the new hire when someone joins Slack (this can be done automatically or with manual approval within Slack).
3. [Using the COB API](https://docs.chiefonboarding.com/api/). Every instance has their own API endpoints.

The API that's currently in place doesn't seem compatible with the [webhooks payload from TypeForm](https://developer.typeform.com/webhooks/example-payload/). 

I have planned to build synchronization options from various HR tools which will basically do the reverse of what integrations do right now - also with the JSON config files. Webhooks will be the main driver of that, so TypeForm should be possible then.

For now, you could do two things if you need this:

1. Code your own tool to catch the webhooks from typeform, change the data and then post it to the Chief API.
2. Maybe use Zapier to bridge that? TypeForm -> Zapier -> Chief API? See [this integration](https://zapier.com/apps/typeform/integrations/webhook) specifically. I am not entirely sure if that fits your usecase and what the limitations are of Zapier, but it might just work.

**Comment by MuratDoganer** [comment]
Ah that makes sense

In that case it wouldnt be too hard to do it so they fill the form out in COB first, might even make it easier for them

But I am intrigued by Zapier! will definitely play around with that for sure

**Comment by MuratDoganer** [comment]
Hey @GDay its your favourite tester :D 

Found 2 more bugs:

1. Sync With Slack in the member area; this doesnt always work, is there a limit to how many members it can sync? We are seeing a lot of deactivated accounts being pulled in but tons of active accounts are missing or not being added in (to test this we have multiple accounts beginning with A, but only 1 out of 5 got added to COB using Sync with Slack)
2. File uploads have broken again! Files upload with no error message, when you go to save your work / update its there, but when you refresh the uploaded file has disappeared. If you upload it again and save again, that entire resource / task etc becomes unresponsive and unusable, returning a Server 500 error

**Comment by GDay** [comment]
> its your favourite tester :D

You are awesome!

> is there a limit to how many members it can sync?

According to Slack: 
> Providing no limit value will result in Slack attempting to deliver you the entire result set. If the collection is too large you may experience limit_required or HTTP 500 errors.

I haven't provided a limit, but just to be safe, I will implement a limit of 200 and do multiple requests to get all users. I have only tested this with a Slack channel with a low user count. I will also filter out the deleted ones.

> File uploads have broken again! Files upload with no error message, when you go to save your work / update its there, but when you refresh the uploaded file has disappeared. If you upload it again and save again, that entire resource / task etc becomes unresponsive and unusable, returning a Server 500 error

Hmm... Very strange. I was able to reproduce this. Will fix this asap.

**Comment by GDay** [comment]
1. Should be fixed with PR #219 
2. Should be fixed with PR #218

Regarding 2: the 500 error was due to not correctly saving the file in the editor box. You will unfortunately have to check the items that have files and reupload the ones that say "File is invalid. Please remove and try again - FILENAME". 
There was another bug there that caused files to disappear, which was actually a bug in the upload plugin (added a fix to that repo to: [ref](https://github.com/editor-js/attaches/pull/61))

Both PRs will probably be merged on Monday.

**Comment by MuratDoganer** [comment]
Thanks @GDay !

**Comment by MuratDoganer** [comment]
Found another one today! 

Server Error 500 when assigning a Sequence 

Looked into it, the sequence contains a task that is not responding (its loading forever) and you cannot delete it!

**Comment by GDay** [comment]
> the sequence contains a task that is not responding (its loading forever) and you cannot delete it!

I think this is due to the file upload issue. I have just merged all open PRs.

**Comment by MuratDoganer** [comment]
Okay let me test this one again :)

**Comment by MuratDoganer** [comment]
Sync with slack: Still not working, no response and no users added < do I need to do something before hand?

**Comment by MuratDoganer** [comment]
Hmmm okay yeah once that happens I can see who the user is and then see why the format is different for that user, very odd!

**Comment by MuratDoganer** [comment]
Oop, found one more, at the end of every Slackbot message it adds `&nbsp;`

Im guessing this is due to the new paragraph

**Comment by GDay** [comment]
Weird, doesn't seem to do that for me...

Just created a new sequence, with a new slack message (with the updated editor) to my new hire:

![image](https://user-images.githubusercontent.com/1939656/184665113-95d7e4c8-2570-469a-a9f3-a21128b722e8.png)


Is that with everything or just Slack messages from sequences?

**Comment by MuratDoganer** [comment]
On those single liners, its okay, but if you go 2 paragraphs it adds it, heres an example just now:
<img width="558" alt="Screenshot 2022-08-15 at 16 28 58" src="https://user-images.githubusercontent.com/67741877/184665568-3d86d341-6fa9-4436-9e26-d3a27d803efa.png">

**Comment by GDay** [comment]
![image](https://user-images.githubusercontent.com/1939656/184665864-7bc44992-d561-45f0-8fcf-d2fd52f78f00.png)

Nope, still nothing for me... weird. I can easily escape the word, but I would rather find out why it does that... I will do some more testing tonight.

**Comment by MuratDoganer** [comment]
Hmmm, when adding paragraphs, do you Shift+Enter or just Enter and add a new block?

Might be the blocks causing it?

**Comment by GDay** [comment]
![image](https://user-images.githubusercontent.com/1939656/184667425-3b3a3b53-8dbf-457b-9cd1-da52a961de2e.png)

Shift enter doesn't work in the editor (when it gets converted to a Slack message). Wouldn't recommend using shift enter, but doesn't seem to make a different.

**Comment by GDay** [comment]
Weird that you didn't got any errors with Slack sync now, but I am glad that's fixed.

**Comment by GDay** [comment]
I wasn't able to figure out how you got those in the paragraphs, anyway, just to get it fixed, I have now merged PR #221 which will replace the `&nbsp;` with a normal space on the fly. I was a little on the fence on doing this as a non-breakable space does have its use cases, but I guess it won't be a big deal.

**Comment by MuratDoganer** [comment]
Yeah its definitely odd, considering it wasn't happening before, and it seems to be intermittent, here is an example from 2 slack messages sent around the same time from the same sequence:

This one works absolutely fine:

<img width="597" alt="Screenshot 2022-08-16 at 10 34 48" src="https://user-images.githubusercontent.com/67741877/184847892-8ee65838-b693-42ac-b581-2baa19f3a5e1.png">

This one has the spacers in the first, second and fourth paragraph, but third paragraph is okay:

<img width="470" alt="Screenshot 2022-08-16 at 10 35 01" src="https://user-images.githubusercontent.com/67741877/184848042-67f0f47d-71e0-4991-9507-c6f2382256ca.png">

Very odd!

**Comment by MuratDoganer** [comment]
Hey @GDay Is it possible to add the Department during the New Hires intake form? At the moment there isnt an area to add the Department until you've already entered the new hire in, and then edit their profile

**Comment by GDay** [comment]
That's a good idea. Thanks. 

Will be available when I merge: #229

**Comment by woakes070048** [comment]
@GDay what would a zapier example look like?

**Comment by GDay** [comment]
@woakes070048 Not entirely sure what you mean, but if you want to trigger something through the integrations option, then you could use Zapier webhooks: https://zapier.com/apps/webhook/integrations. In the `execute` block you can then use the URL that Zapier gives you.

**Comment by woakes070048** [comment]
@GDay I was looking for guidance on configuring the integration section, so once the system ads a new hire in Cheif onboarding, a webhook gets triggered I zapier, and we can send that data over to our ERP system. And in reverse, maybe we add a user in the ERP HRM section it can then send a zap over to chief onboarding to create a new user. I'm not a dev, so I have a hard time without a concrete example of how to do something.

**Comment by GDay** [comment]
@woakes070048 I have just created this integration: https://integrations.chiefonboarding.com/d/37-zapier-webhook. It will call the Zapier webhook and from there you can connect any app you want. By default, it sends the new hire's name and new hire's email to the webhook, but you could add more details if you want. 

> And in reverse, maybe we add a user in the ERP HRM section it can then send a zap over to chief onboarding to create a new user.

If your ERP system is on Zapier then that should be possible. You should then go from ERP -> Zapier (webhooks), which should send a request to the ChiefOnboarding API (https://docs.chiefonboarding.com/api/).
